package com.iyanda.dao;

import com.iyanda.entity.Branch;

import java.util.List;

public interface BranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated
     */
    int insert(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated
     */
    Branch selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated
     */
    List<Branch> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_branch
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Branch record);
}