package com.iyanda.dao;

import com.iyanda.entity.ChatRecord;

import java.util.List;

public interface ChatRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatrecord
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatrecord
     *
     * @mbggenerated
     */
    int insert(ChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatrecord
     *
     * @mbggenerated
     */
    ChatRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatrecord
     *
     * @mbggenerated
     */
    List<ChatRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatrecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChatRecord record);
}