package com.iyanda.dao;

import com.iyanda.entity.CommunityInform;

import java.util.List;

import org.springframework.stereotype.Repository;

@Repository
public interface CommunityInformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_communityinform
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_communityinform
     *
     * @mbggenerated
     */
    int insert(CommunityInform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_communityinform
     *
     * @mbggenerated
     */
    CommunityInform selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_communityinform
     *
     * @mbggenerated
     */
    List<CommunityInform> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_communityinform
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommunityInform record);
}