package com.iyanda.dao;

import com.iyanda.entity.CommunityEvent;

import java.util.List;

import org.springframework.stereotype.Repository;
@Repository
public interface CommunityEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_communityevent
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_communityevent
     *
     * @mbggenerated
     */
    int insert(CommunityEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_communityevent
     *
     * @mbggenerated
     */
    CommunityEvent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_communityevent
     *
     * @mbggenerated
     */
    List<CommunityEvent> selectAll();
    
    List<CommunityEvent> selectEventByCommunityId(String communityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_communityevent
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommunityEvent record);
}