package com.iyanda.dao;

import com.iyanda.entity.CommunityData;

import java.util.List;

import org.springframework.stereotype.Repository;

@Repository
public interface CommunityDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_communitydata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_communitydata
     *
     * @mbggenerated
     */
    int insert(CommunityData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_communitydata
     *
     * @mbggenerated
     */
    CommunityData selectByPrimaryKey(String id);
    
    CommunityData selectByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_communitydata
     *
     * @mbggenerated
     */
    List<CommunityData> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_communitydata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommunityData record);
}