package com.iyanda.dao;

import com.iyanda.entity.DateInform;

import java.util.List;

public interface DateInformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dateinform
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dateinform
     *
     * @mbggenerated
     */
    int insert(DateInform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dateinform
     *
     * @mbggenerated
     */
    DateInform selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dateinform
     *
     * @mbggenerated
     */
    List<DateInform> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dateinform
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DateInform record);
}