package com.iyanda.dao;

import com.iyanda.entity.Doc;

import java.util.List;

import org.springframework.stereotype.Repository;
@Repository
public interface DocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_doc
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_doc
     *
     * @mbggenerated
     */
    int insert(Doc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_doc
     *
     * @mbggenerated
     */
    Doc selectByPrimaryKey(String id);
    
    Doc selectByTname(String doctname);
    
    List<Doc> selectByCommunityId(String communityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_doc
     *
     * @mbggenerated
     */
    List<Doc> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_doc
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Doc record);
}