package com.iyanda.dao;

import com.iyanda.entity.Inform;

import java.util.List;

public interface InformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inform
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inform
     *
     * @mbggenerated
     */
    int insert(Inform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inform
     *
     * @mbggenerated
     */
    Inform selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inform
     *
     * @mbggenerated
     */
    List<Inform> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inform
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Inform record);

	List<Inform> selectLimit15();
}