package com.iyanda.dao;

import com.iyanda.entity.LocalityData;

import java.util.List;

import org.springframework.stereotype.Repository;

@Repository
public interface LocalityDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localitydata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localitydata
     *
     * @mbggenerated
     */
    int insert(LocalityData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localitydata
     *
     * @mbggenerated
     */
    LocalityData selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localitydata
     *
     * @mbggenerated
     */
    List<LocalityData> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_localitydata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LocalityData record);
}