package com.iyanda.entity;

public class Branch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch.CommunityID
     *
     * @mbggenerated
     */
    private String communityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch.DepartmentName
     *
     * @mbggenerated
     */
    private String departmentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch.MinisterID
     *
     * @mbggenerated
     */
    private String ministerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_branch.DepartmentIntro
     *
     * @mbggenerated
     */
    private String departmentintro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch.ID
     *
     * @return the value of t_branch.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch.ID
     *
     * @param id the value for t_branch.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch.CommunityID
     *
     * @return the value of t_branch.CommunityID
     *
     * @mbggenerated
     */
    public String getCommunityid() {
        return communityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch.CommunityID
     *
     * @param communityid the value for t_branch.CommunityID
     *
     * @mbggenerated
     */
    public void setCommunityid(String communityid) {
        this.communityid = communityid == null ? null : communityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch.DepartmentName
     *
     * @return the value of t_branch.DepartmentName
     *
     * @mbggenerated
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch.DepartmentName
     *
     * @param departmentname the value for t_branch.DepartmentName
     *
     * @mbggenerated
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch.MinisterID
     *
     * @return the value of t_branch.MinisterID
     *
     * @mbggenerated
     */
    public String getMinisterid() {
        return ministerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch.MinisterID
     *
     * @param ministerid the value for t_branch.MinisterID
     *
     * @mbggenerated
     */
    public void setMinisterid(String ministerid) {
        this.ministerid = ministerid == null ? null : ministerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_branch.DepartmentIntro
     *
     * @return the value of t_branch.DepartmentIntro
     *
     * @mbggenerated
     */
    public String getDepartmentintro() {
        return departmentintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_branch.DepartmentIntro
     *
     * @param departmentintro the value for t_branch.DepartmentIntro
     *
     * @mbggenerated
     */
    public void setDepartmentintro(String departmentintro) {
        this.departmentintro = departmentintro == null ? null : departmentintro.trim();
    }
}