package com.iyanda.entity;

import java.util.Date;

public class ChatRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chatrecord.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chatrecord.senderID
     *
     * @mbggenerated
     */
    private String senderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chatrecord.receiverID
     *
     * @mbggenerated
     */
    private String receiverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chatrecord.Content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chatrecord.Date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chatrecord.ReadSign
     *
     * @mbggenerated
     */
    private Integer readsign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chatrecord.CommunityGroup
     *
     * @mbggenerated
     */
    private Integer communitygroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chatrecord.ID
     *
     * @return the value of t_chatrecord.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chatrecord.ID
     *
     * @param id the value for t_chatrecord.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chatrecord.senderID
     *
     * @return the value of t_chatrecord.senderID
     *
     * @mbggenerated
     */
    public String getSenderid() {
        return senderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chatrecord.senderID
     *
     * @param senderid the value for t_chatrecord.senderID
     *
     * @mbggenerated
     */
    public void setSenderid(String senderid) {
        this.senderid = senderid == null ? null : senderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chatrecord.receiverID
     *
     * @return the value of t_chatrecord.receiverID
     *
     * @mbggenerated
     */
    public String getReceiverid() {
        return receiverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chatrecord.receiverID
     *
     * @param receiverid the value for t_chatrecord.receiverID
     *
     * @mbggenerated
     */
    public void setReceiverid(String receiverid) {
        this.receiverid = receiverid == null ? null : receiverid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chatrecord.Content
     *
     * @return the value of t_chatrecord.Content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chatrecord.Content
     *
     * @param content the value for t_chatrecord.Content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chatrecord.Date
     *
     * @return the value of t_chatrecord.Date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chatrecord.Date
     *
     * @param date the value for t_chatrecord.Date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chatrecord.ReadSign
     *
     * @return the value of t_chatrecord.ReadSign
     *
     * @mbggenerated
     */
    public Integer getReadsign() {
        return readsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chatrecord.ReadSign
     *
     * @param readsign the value for t_chatrecord.ReadSign
     *
     * @mbggenerated
     */
    public void setReadsign(Integer readsign) {
        this.readsign = readsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chatrecord.CommunityGroup
     *
     * @return the value of t_chatrecord.CommunityGroup
     *
     * @mbggenerated
     */
    public Integer getCommunitygroup() {
        return communitygroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chatrecord.CommunityGroup
     *
     * @param communitygroup the value for t_chatrecord.CommunityGroup
     *
     * @mbggenerated
     */
    public void setCommunitygroup(Integer communitygroup) {
        this.communitygroup = communitygroup;
    }
}