package com.iyanda.entity;

import java.util.Date;

public class CommunityInform {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_communityinform.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_communityinform.senderID
     *
     * @mbggenerated
     */
    private String senderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_communityinform.receiverID
     *
     * @mbggenerated
     */
    private String receiverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_communityinform.Date
     *
     * @mbggenerated
     */
    private Date date;
    
    private String content;
    
    

    public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communityinform.ID
     *
     * @return the value of t_communityinform.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communityinform.ID
     *
     * @param id the value for t_communityinform.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communityinform.senderID
     *
     * @return the value of t_communityinform.senderID
     *
     * @mbggenerated
     */
    public String getSenderid() {
        return senderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communityinform.senderID
     *
     * @param senderid the value for t_communityinform.senderID
     *
     * @mbggenerated
     */
    public void setSenderid(String senderid) {
        this.senderid = senderid == null ? null : senderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communityinform.receiverID
     *
     * @return the value of t_communityinform.receiverID
     *
     * @mbggenerated
     */
    public String getReceiverid() {
        return receiverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communityinform.receiverID
     *
     * @param receiverid the value for t_communityinform.receiverID
     *
     * @mbggenerated
     */
    public void setReceiverid(String receiverid) {
        this.receiverid = receiverid == null ? null : receiverid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communityinform.Date
     *
     * @return the value of t_communityinform.Date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communityinform.Date
     *
     * @param date the value for t_communityinform.Date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}