package com.iyanda.entity;

public class CommunityData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_communitydata.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_communitydata.CommunityName
     *
     * @mbggenerated
     */
    private String communityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_communitydata.CommunityIntro
     *
     * @mbggenerated
     */
    private String communityintro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_communitydata.Type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communitydata.ID
     *
     * @return the value of t_communitydata.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communitydata.ID
     *
     * @param id the value for t_communitydata.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communitydata.CommunityName
     *
     * @return the value of t_communitydata.CommunityName
     *
     * @mbggenerated
     */
    public String getCommunityname() {
        return communityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communitydata.CommunityName
     *
     * @param communityname the value for t_communitydata.CommunityName
     *
     * @mbggenerated
     */
    public void setCommunityname(String communityname) {
        this.communityname = communityname == null ? null : communityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communitydata.CommunityIntro
     *
     * @return the value of t_communitydata.CommunityIntro
     *
     * @mbggenerated
     */
    public String getCommunityintro() {
        return communityintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communitydata.CommunityIntro
     *
     * @param communityintro the value for t_communitydata.CommunityIntro
     *
     * @mbggenerated
     */
    public void setCommunityintro(String communityintro) {
        this.communityintro = communityintro == null ? null : communityintro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_communitydata.Type
     *
     * @return the value of t_communitydata.Type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_communitydata.Type
     *
     * @param type the value for t_communitydata.Type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }
}