package com.iyanda.entity;

import java.util.Date;

public class DateInform {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dateinform.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dateinform.senderID
     *
     * @mbggenerated
     */
    private String senderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dateinform.Date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dateinform.ImageSrc
     *
     * @mbggenerated
     */
    private String imagesrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dateinform.Title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dateinform.Content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dateinform.ID
     *
     * @return the value of t_dateinform.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dateinform.ID
     *
     * @param id the value for t_dateinform.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dateinform.senderID
     *
     * @return the value of t_dateinform.senderID
     *
     * @mbggenerated
     */
    public String getSenderid() {
        return senderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dateinform.senderID
     *
     * @param senderid the value for t_dateinform.senderID
     *
     * @mbggenerated
     */
    public void setSenderid(String senderid) {
        this.senderid = senderid == null ? null : senderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dateinform.Date
     *
     * @return the value of t_dateinform.Date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dateinform.Date
     *
     * @param date the value for t_dateinform.Date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dateinform.ImageSrc
     *
     * @return the value of t_dateinform.ImageSrc
     *
     * @mbggenerated
     */
    public String getImagesrc() {
        return imagesrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dateinform.ImageSrc
     *
     * @param imagesrc the value for t_dateinform.ImageSrc
     *
     * @mbggenerated
     */
    public void setImagesrc(String imagesrc) {
        this.imagesrc = imagesrc == null ? null : imagesrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dateinform.Title
     *
     * @return the value of t_dateinform.Title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dateinform.Title
     *
     * @param title the value for t_dateinform.Title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dateinform.Content
     *
     * @return the value of t_dateinform.Content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dateinform.Content
     *
     * @param content the value for t_dateinform.Content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}