package com.iyanda.entity;

import java.util.Date;


public class Doc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_doc.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_doc.DocumentSrc
     *
     * @mbggenerated
     */
    private String documentsrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_doc.CommunityID
     *
     * @mbggenerated
     */
    private String communityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_doc.PermissionNum
     *
     * @mbggenerated
     */
    private Integer permissionnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_doc.DocumentName
     *
     * @mbggenerated
     */
    private String documentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_doc.Date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doc.ID
     *
     * @return the value of t_doc.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doc.ID
     *
     * @param id the value for t_doc.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doc.DocumentSrc
     *
     * @return the value of t_doc.DocumentSrc
     *
     * @mbggenerated
     */
    public String getDocumentsrc() {
        return documentsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doc.DocumentSrc
     *
     * @param documentsrc the value for t_doc.DocumentSrc
     *
     * @mbggenerated
     */
    public void setDocumentsrc(String documentsrc) {
        this.documentsrc = documentsrc == null ? null : documentsrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doc.CommunityID
     *
     * @return the value of t_doc.CommunityID
     *
     * @mbggenerated
     */
    public String getCommunityid() {
        return communityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doc.CommunityID
     *
     * @param communityid the value for t_doc.CommunityID
     *
     * @mbggenerated
     */
    public void setCommunityid(String communityid) {
        this.communityid = communityid == null ? null : communityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doc.PermissionNum
     *
     * @return the value of t_doc.PermissionNum
     *
     * @mbggenerated
     */
    public Integer getPermissionnum() {
        return permissionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doc.PermissionNum
     *
     * @param permissionnum the value for t_doc.PermissionNum
     *
     * @mbggenerated
     */
    public void setPermissionnum(Integer permissionnum) {
        this.permissionnum = permissionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doc.DocumentName
     *
     * @return the value of t_doc.DocumentName
     *
     * @mbggenerated
     */
    public String getDocumentname() {
        return documentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doc.DocumentName
     *
     * @param documentname the value for t_doc.DocumentName
     *
     * @mbggenerated
     */
    public void setDocumentname(String documentname) {
        this.documentname = documentname == null ? null : documentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doc.Date
     *
     * @return the value of t_doc.Date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doc.Date
     *
     * @param date the value for t_doc.Date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}