package com.iyanda.entity;

public class Friend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend.UserID
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend.FriendID
     *
     * @mbggenerated
     */
    private String friendid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend.ID
     *
     * @return the value of t_friend.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend.ID
     *
     * @param id the value for t_friend.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend.UserID
     *
     * @return the value of t_friend.UserID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend.UserID
     *
     * @param userid the value for t_friend.UserID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend.FriendID
     *
     * @return the value of t_friend.FriendID
     *
     * @mbggenerated
     */
    public String getFriendid() {
        return friendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend.FriendID
     *
     * @param friendid the value for t_friend.FriendID
     *
     * @mbggenerated
     */
    public void setFriendid(String friendid) {
        this.friendid = friendid == null ? null : friendid.trim();
    }
}