package com.iyanda.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.UserName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.UserNickname
     *
     * @mbggenerated
     */
    private String usernickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PassWord
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PersonalSign
     *
     * @mbggenerated
     */
    private Integer personalsign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ImageSrc
     *
     * @mbggenerated
     */
    
    //imageSrc = 1  管理员
    private String imagesrc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ID
     *
     * @return the value of t_user.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ID
     *
     * @param id the value for t_user.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.UserName
     *
     * @return the value of t_user.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.UserName
     *
     * @param username the value for t_user.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.UserNickname
     *
     * @return the value of t_user.UserNickname
     *
     * @mbggenerated
     */
    public String getUsernickname() {
        return usernickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.UserNickname
     *
     * @param usernickname the value for t_user.UserNickname
     *
     * @mbggenerated
     */
    public void setUsernickname(String usernickname) {
        this.usernickname = usernickname == null ? null : usernickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PassWord
     *
     * @return the value of t_user.PassWord
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PassWord
     *
     * @param password the value for t_user.PassWord
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PersonalSign
     *
     * @return the value of t_user.PersonalSign
     *
     * @mbggenerated
     */
    public Integer getPersonalsign() {
        return personalsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PersonalSign
     *
     * @param personalsign the value for t_user.PersonalSign
     *
     * @mbggenerated
     */
    public void setPersonalsign(Integer personalsign) {
        this.personalsign = personalsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ImageSrc
     *
     * @return the value of t_user.ImageSrc
     *
     * @mbggenerated
     */
    public String getImagesrc() {
        return imagesrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ImageSrc
     *
     * @param imagesrc the value for t_user.ImageSrc
     *
     * @mbggenerated
     */
    public void setImagesrc(String imagesrc) {
        this.imagesrc = imagesrc == null ? null : imagesrc.trim();
    }
}